`timescale 1ns/1ps

/*
 * ============================================================
 * File        : aes_core.sv
 * Description : AES-128 baseline encryption core
 *
 * Project     : ECE4063 IC Design Project
 *
 * Architecture:
 *   - Baseline AES-128 encryption-only core.
 *   - Iterative one-round-per-cycle architecture.
 *   - One AES round datapath is reused for all 10 AES rounds.
 *   - Key expansion generates the next round key during each round.
 *   - Start / busy / done control interface.
 *
 * Main purpose:
 *   This module performs the full AES-128 encryption operation.
 *   It receives a 128-bit plaintext block and a 128-bit key, then
 *   produces the corresponding 128-bit ciphertext.
 *
 * AES operation sequence:
 *
 *   Initial step:
 *     state_reg = plaintext XOR key
 *
 *   Rounds 1 to 9:
 *     SubBytes -> ShiftRows -> MixColumns -> AddRoundKey
 *
 *   Round 10:
 *     SubBytes -> ShiftRows -> AddRoundKey
 *
 * Interface:
 *   clk        : System clock
 *   reset_n    : Active-low asynchronous reset
 *   start      : One-clock pulse to begin encryption
 *   plaintext  : 128-bit input plaintext block
 *   key        : 128-bit AES key
 *   ciphertext : 128-bit encrypted output block
 *   busy       : High while encryption is running
 *   done       : One-clock pulse when ciphertext is valid
 *
 * Internal registers:
 *   state_reg     : Stores the current AES state.
 *   round_key_reg : Stores the current round key.
 *   round_reg     : Tracks the current AES round number.
 *   rcon_reg      : Stores the current AES round constant.
 *
 * Notes:
 *   - reset_n is active-low.
 *   - start should be pulsed high for one clock cycle only.
 *   - done is asserted for one clock cycle when encryption finishes.
 *   - This baseline design is used for comparison against the later
 *     area-optimized shared-resource implementation.
 * ============================================================
 */

module aes_core
(
    // System clock.
    input  logic         clk,

    // Active-low asynchronous reset.
    input  logic         reset_n,

    // One-clock pulse to start encryption.
    input  logic         start,

    // 128-bit plaintext input block.
    input  logic [127:0] plaintext,

    // 128-bit AES key.
    input  logic [127:0] key,

    // 128-bit ciphertext output block.
    output logic [127:0] ciphertext,

    // High while AES encryption is running.
    output logic         busy,

    // One-clock pulse when ciphertext is valid.
    output logic         done
);

    /*
     * Internal AES state register.
     *
     * Stores the current 128-bit AES state between rounds.
     * After start is accepted, this register is loaded with:
     *
     *   plaintext XOR key
     *
     * which is the initial AddRoundKey step.
     */
    logic [127:0] state_reg;

    /*
     * Current round key register.
     *
     * Stores the round key currently used to generate the next
     * round key.
     *
     * At the start:
     *   round_key_reg = original key, K0
     *
     * During each round:
     *   next_round_key is generated from round_key_reg.
     *   round_key_reg is then updated to next_round_key.
     */
    logic [127:0] round_key_reg;

    /*
     * Round counter.
     *
     * round_reg indicates which AES round is currently being
     * executed.
     *
     * Valid active values:
     *   1 to 9  : normal AES rounds with MixColumns.
     *   10      : final AES round without MixColumns.
     *
     * When the core is idle, round_reg is cleared to 0.
     */
    logic [3:0] round_reg;

    /*
     * AES Rcon register.
     *
     * Stores the round constant used by key expansion.
     *
     * AES-128 Rcon sequence:
     *   01 -> 02 -> 04 -> 08 -> 10
     *   -> 20 -> 40 -> 80 -> 1b -> 36
     *
     * The value is updated using aes_xtime().
     */
    logic [7:0] rcon_reg;

    // Next 128-bit round key generated by key expansion.
    logic [127:0] next_round_key;

    // AES state after one round.
    logic [127:0] round_state_out;

    // High during round 10 so aes_round skips MixColumns.
    logic         final_round;

    /*
     * Final round detection.
     *
     * AES-128 round 10 skips MixColumns. This signal tells
     * aes_round whether to include or skip the MixColumns step.
     */
    assign final_round = (round_reg == 4'd10);

    /*
     * Key expansion block.
     *
     * Generates the next round key from the current round key
     * and the current Rcon value.
     *
     * Example:
     *   If round_key_reg = K0 and rcon_reg = 01,
     *   then next_round_key = K1.
     */
    keyexpansion u_keyexpansion
    (
        .key_in     (round_key_reg),
        .rcon_byte  (rcon_reg),
        .key_out    (next_round_key)
    );

    /*
     * AES round datapath.
     *
     * Performs one AES encryption round combinationally.
     *
     * For rounds 1 to 9:
     *   SubBytes -> ShiftRows -> MixColumns -> AddRoundKey
     *
     * For round 10:
     *   SubBytes -> ShiftRows -> AddRoundKey
     *
     * The output is stored back into state_reg on the next clock
     * edge while the core is busy.
     */
    aes_round u_aes_round
    (
        .state_in    (state_reg),
        .round_key   (next_round_key),
        .final_round (final_round),
        .state_out   (round_state_out)
    );

    /*
     * Sequential AES controller and state update logic.
     *
     * This always_ff block controls the full encryption process:
     *
     *   1. Reset all registers.
     *   2. Accept start request when idle.
     *   3. Perform one AES round per clock cycle.
     *   4. Assert done when round 10 finishes.
     */
    always_ff @(posedge clk or negedge reset_n) begin

        /*
         * Active-low reset.
         *
         * Clears all internal registers and returns the AES core
         * to the idle state.
         */
        if (!reset_n) begin
            state_reg     <= 128'h0;
            round_key_reg <= 128'h0;
            round_reg     <= 4'd0;
            rcon_reg      <= 8'h00;
            ciphertext    <= 128'h0;
            busy          <= 1'b0;
            done          <= 1'b0;
        end

        else begin
            /*
             * done is a one-clock pulse.
             *
             * It is cleared by default every cycle and only set
             * when the final round completes.
             */
            done <= 1'b0;

            /*
             * Start condition.
             *
             * A new AES encryption operation is accepted only
             * when the core is idle.
             *
             * On the start cycle:
             *   - perform initial AddRoundKey.
             *   - load the original key.
             *   - set round counter to 1.
             *   - load first Rcon value.
             *   - assert busy.
             *
             * Important:
             *   start should be pulsed high for one clock cycle.
             */
            if (start && !busy) begin
                state_reg     <= plaintext ^ key;
                round_key_reg <= key;
                round_reg     <= 4'd1;
                rcon_reg      <= 8'h01;
                busy          <= 1'b1;
            end

            /*
             * AES round execution.
             *
             * While busy is high, the core performs one AES
             * round per clock cycle.
             *
             * round_state_out and next_round_key are generated
             * combinationally from the current state/key. They
             * are stored into registers at this clock edge.
             */
            else if (busy) begin
                state_reg     <= round_state_out;
                round_key_reg <= next_round_key;

                /*
                 * Final round complete.
                 *
                 * When round_reg is 10, round_state_out already
                 * contains the final AES ciphertext.
                 *
                 * The ciphertext is saved, busy is cleared, and
                 * done is pulsed high for one clock cycle.
                 */
                if (round_reg == 4'd10) begin
                    ciphertext <= round_state_out;
                    round_reg  <= 4'd0;
                    rcon_reg   <= 8'h00;
                    busy       <= 1'b0;
                    done       <= 1'b1;
                end

                /*
                 * Continue to next AES round.
                 *
                 * For rounds 1 to 9:
                 *   - increment round counter.
                 *   - update Rcon for the next key expansion.
                 */
                else begin
                    round_reg <= round_reg + 4'd1;
                    rcon_reg  <= aes_xtime(rcon_reg);
                end
            end
        end
    end

    /*
     * Function    : aes_xtime
     * Description : Multiplication by 02 in AES GF(2^8)
     *
     * Purpose:
     *   Used to update the AES Rcon sequence for key expansion.
     *
     * GF(2^8) rule:
     *   If the most significant bit is 0:
     *       result = b << 1
     *
     *   If the most significant bit is 1:
     *       result = (b << 1) XOR 8'h1b
     *
     * The value 8'h1b represents reduction by the AES
     * irreducible polynomial:
     *
     *   x^8 + x^4 + x^3 + x + 1
     *
     * Rcon sequence generated:
     *   01 -> 02 -> 04 -> 08 -> 10
     *   -> 20 -> 40 -> 80 -> 1b -> 36
     */
    function automatic logic [7:0] aes_xtime
    (
        input logic [7:0] b
    );
        begin
            if (b[7] == 1'b1) begin
                aes_xtime = (b << 1) ^ 8'h1b;
            end
            else begin
                aes_xtime = (b << 1);
            end
        end
    endfunction

endmodule